# Generated by Django 3.1 on 2021-03-11 01:03
from django.db import migrations, models

import pymess.models.emails


class Migration(migrations.Migration):

    dependencies = [
        ('pymess', '0024_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='content_file',
            field=models.FileField(upload_to=pymess.models.emails.generate_content_filename,
                                   verbose_name='content file'),
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='old_content',
        ),
    ]
